data_dir_on_host: "../../data/pix2pix"
data_dir: "/data"

logging_output_directory_on_host: "/tmp/pix2pix"
logging_path: "/tmp/log.html"

facades_dataset:
  training_data_dir: "/data/facades/train"
  validation_data_dir: "/data/facades/val"
  test_data_dir: "/data/facades/test"

facades_model:
  batch_size: 4
  epochs: 2000
  image_shape: [256, 256, 3]

  data_augmentation_parameters:
    image_shape: [256, 256, 3]
    resized_image_shape: [286, 286]
